// E:\my_app_new\src\app\homepage\layout.tsx

import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/app/components/Navbar";
import AuthProvider from "../components/AuthProvider";
import SessionGuard from "@/app/components/SessionGuard";
import { CartProvider } from "@/context/CartContext";
import Footer from "@/app/components/Footer";
import { LoadingProvider } from "@/context/LoadingContext";
import { NotificationProvider } from "@/context/NotificationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <AuthProvider>
          <SessionGuard>
            <LoadingProvider>
              <CartProvider>
                <NotificationProvider>
                  <Navbar />
                  <div className="min-h-screen">{children}</div>
                  <Footer />
                </NotificationProvider>
              </CartProvider>
            </LoadingProvider>
          </SessionGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
