// E:\my_app_new\src\app\homepage\layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import AuthProvider from "../components/AuthProvider";
import SessionGuard from "@/app/components/SessionGuard";
import { CartProvider } from "@/context/CartContext";
import Footer from "@/app/components/Footer";
import { LoadingProvider } from "@/context/LoadingContext";

// import CartRecovery from "@/app/components/CartRecovery";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <SessionGuard>
            <CartProvider>
              <LoadingProvider>
                {/* <CartRecovery /> */}
                <Navbar />
                {children}
                <Footer />
              </LoadingProvider>
            </CartProvider>
          </SessionGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
