// E:\my_app_new\src\app\home\layout.tsx

import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/src/app/components/Navbar";
import AuthProvider from "@/src/app/components/AuthProvider";
import SessionGuard from "@/src/app/components/SessionGuard";
import { CartProvider } from "@/src/context/CartContext";
import Footer from "@/src/app/components/Footer";
import { LoadingProvider } from "@/src/context/LoadingContext";
import { NotificationProvider } from "@/src/context/NotificationContext";

export const metadata: Metadata = {
  title: "MobileLoom",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon/favicon.ico",
    shortcut: "/favicon/favicon.ico",
    apple: "/favicon/apple-touch-icon.png",
  },
  manifest: "/favicon/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <SessionGuard>
            <LoadingProvider>
              <NotificationProvider>
                <CartProvider>
                  <Navbar />
                  <div className="min-h-screen">{children}</div>
                  <Footer />
                </CartProvider>
              </NotificationProvider>
            </LoadingProvider>
          </SessionGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
